### ISSUE TITLE
loadDataDE throws error

### ISSUE THREAD

**Issue by jschibberges** [INWTlab/lsTerm-election-forecast#4]
The script in the notebook throws an error when running
`dataDE <- loadDataDE(predDate)`
At first it throws 

> Fehler in html_text(.) : konnte Funktion "html_text" nicht finden

After some searching I imported the package rvest which supplies the needed function. However this leads to a new error

> Error in ifelse(length(.) > 0, return(c(x, paste0(mainPage, .))), return(x)) : 
>   no function to return from, jumping to top level

The Traceback shows

> 7. ifelse(length(.) > 0, return(c(x, paste0(mainPage, .))), return(x)) 
> 6. x %>% read_html %>% html_nodes(., "p.navi a") %>% xml_attr("href") %>% 
>     {
>         ifelse(length(.) > 0, return(c(x, paste0(mainPage, .))), 
>             return(x)) ... 
> 5. FUN(X[[i]], ...) 
> 4. lapply(., generateTableUrls) 
> 3. urls %>% lapply(generateTableUrls) 
> 2. getPollData(predDate) 
> 1. loadDataDE(predDate) 

The ifelse-check itself works, but the return-function seems to throw an error.

I am using 

- RStudio Version 1.4.1106
- R version 4.0.5 (2021-03-31)
- Windows 10 x64

**Comment by mgross** [comment]
@jschibberges 
Have you tried to build the package first (e.g. in RStudio) and then executing the first 5 lines from /R_Scripts/ScriptMulti.R? Some other packages have functions with identical names to that, that are used in loadDataDE(), so building and loading this repo's package should load the correct namespace.

**Comment by mgross** [comment]
@jschibberges:

I tried it on another system. Seems to be related to interferring packages. Should work now.
