### ISSUE TITLE
`... a coalition of CDU/CSU will receive a majority?` is ambiguous

### ISSUE THREAD

**Issue by ama0** [INWTlab/lsTerm-election-forecast#5]
In german it's `... die große Koalition die Mehrheit erhält?`, which means CDU/CSU and SPD. The english version sounds like it's a coalition of CDU and CSU that will receive a majority.

Probably it's better to say `... the Grand coalition will receive a majority?`. There is even a wikipedia article about the [Grand coalition](https://en.wikipedia.org/wiki/Grand_coalition_(Germany)), so non natives can look it up if they want.

Or match the other phrases: `... a coalition of CDU/CSU-SPD will receive a majority? `. So non germans don't have to look up what a Grand Coalition is. This format is used for all other coalitions: `Greens-SPD-FDP`, `CDU/CSU-Greens`, ...

**Comment by mgross** [comment]
@ama0 Thanks, we fixed this recently

**Comment by chamaoskurumi** [comment]
fixed.
