### ISSUE TITLE
Coalition rankings not sensitive enough to political divergences?

### ISSUE THREAD

**Issue by tbop** [INWTlab/lsTerm-election-forecast#6]
Hi,

I'm a layman when it comes to German elections but there's something that I find strange in the current ranking of coalitions likelihoods.

Concretely, given all the possible combinations of coalitions that would gather a majority of seats at the Bundestag, shouldn't we expect that the coalition with the highest probability be the one that entails less political divergences ?
Although CDU is presently leading the polls it's hard for me to imagine that the likeliest coalition would be CDU-Grün-FDP, as claimed by the algorithm.
Clearly the Bundestag seems to drift on the left wing of the political spectrum this time and that should technically favor (by far?) any left-leaning coalition over say more _bipolar_ ones. Shouldn't it?

Cheers

P.S.: Awesome to see FiveThirtyEight's methodology applied to German elections. Thank you for that!

**Comment by mgross** [comment]
Hi @tbop ,

we (and the experts) don't think that a left winged coalition is more likely than CDU-Greens-FDP. See e.g.:

- A left-wing coalition of SPD-Grüne-Linke, wasn't completely ruled out by SPD and Grüne, but there is a lot of friction concerning foreign policy and the Nato very recently:
https://www.spiegel.de/politik/annalena-baerbock-und-r2g-gruenen-co-chefin-geht-auf-distanz-zur-linkspartei-a-cbcdf3ba-7a40-4810-9f05-a7c1dcdf126d

- A "traffic-light"-coalition (SPD-Grüne-FDP) also doesn't seem to likely as Christian Lindner from FDP just said that there is "Hardly any practical common ground with SPD and Greens": (https://www.tagesspiegel.de/politik/der-blog-zur-bundestagswahl-lindner-haelt-ampel-koalition-mit-spd-und-gruenen-fuer-theoretische-konstruktion/27555758.html)

**Comment by tbop** [comment]
Hi @mgross 

Thanks for your insightful answer. It seems indeed that coalitions aren't obvious as they would seem at first sight in Germany then! 👍
